CREATE ROLE "Alex" LOGIN PASSWORD 'password';
GRANT USAGE ON SCHEMA public TO "Alex";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "Alex";

GRANT SELECT, INSERT, UPDATE, DELETE ON Franchises TO "Alex";
GRANT SELECT, INSERT, UPDATE, DELETE ON Cafe TO "Alex";
GRANT SELECT, INSERT, UPDATE, DELETE ON Cities TO "Alex";
GRANT SELECT, INSERT, UPDATE, DELETE ON Types TO "Alex";